[package]
name = "rust_ecs"
version = "0.1.0"
authors = ["Martin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
unstable = []